package com.example.cvm.User;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;

import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.EditText;
import android.widget.Spinner;
import android.widget.TextView;
import android.widget.Toast;

import com.airbnb.lottie.LottieAnimationView;
import com.example.cvm.R;
import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.Task;
import com.google.firebase.auth.AuthResult;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.auth.FirebaseUser;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

public class User_registration_page extends AppCompatActivity {

    public Button register;
    public TextView signin_button;
    EditText Name,Address,Age,Email,Password;
    FirebaseAuth mAuth;
    public String unique_key;
    FirebaseDatabase firebaseDatabase;
    DatabaseReference databaseReference;

    //new
    EditText name,email,phone_number,institution;
    TextView qualification;
    Button submit;
    Spinner spinner;
    String Gender;
    FirebaseDatabase database;
    DatabaseReference myRef;

    public static String Mail;
    public static String Username;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_user_registration_page);

        mAuth = FirebaseAuth.getInstance();
        databaseReference=FirebaseDatabase.getInstance().getReference("user_signup");

        signin_button=findViewById(R.id.sign_in_button);
        Name=findViewById(R.id.username);
        Address=findViewById(R.id.address);
        Age=findViewById(R.id.age);
        phone_number=findViewById(R.id.Phone_number);
        Email=findViewById(R.id.email);
        Password=findViewById(R.id.password);
        spinner=findViewById(R.id.Gender_Spinner);

        unique_key= unique_key();
        final LottieAnimationView lottie_smily=findViewById(R.id.covid_animation);
        lottie_smily.setSpeed(1);
        lottie_smily.playAnimation();


        List<String> categories=new ArrayList<>();
        categories.add("Gender");
        categories.add("Male");
        categories.add("Female");

        ArrayAdapter<String> dataAdapter;
        dataAdapter=new ArrayAdapter(this,android.R.layout.simple_spinner_item,categories);

        dataAdapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);

        spinner.setAdapter(dataAdapter);
        spinner.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener() {
            @Override
            public void onItemSelected(AdapterView<?> parent, View view, int position, long id) {
                if(parent.getItemAtPosition(position).equals("Gender")){
                    //do nothing
                    Gender=null;
                }
                else{
                    //on selecting sppiner item
                    String item=parent.getItemAtPosition(position).toString();
                    //anything u want do here
                    Gender=spinner.getSelectedItem().toString();
                }
            }
            @Override
            public void onNothingSelected(AdapterView<?> parent) {
                //TODO AUTOGENERATED METHOD DO HERE
            }
        });

        register=findViewById(R.id.Register_button);
        register.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {


                checkConnection();
            }
        });

        signin_button.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Intent intent=new Intent(User_registration_page.this, User_Login_page.class);
                startActivity(intent);
                finish();
            }
        });
    }

    public void checkConnection(){


            FirebaseUser user=FirebaseAuth.getInstance().getCurrentUser();

            if(Name.length()==0){
                Name.setError("Enter Name!");
            }else if(Email.length()==0){
                Email.setError("Enter Email!");
            }else if(Address.length()==0){
                Address.setError("Enter Address!");
            }else if(phone_number.length()==0){
                phone_number.setError("Enter Phone Number!");
            }else if(Age.length()==0){
                Age.setError("Enter Age!");
            } else if(Gender==null){
                Toast.makeText(User_registration_page.this, " select Gender",
                        Toast.LENGTH_SHORT).show();
            }else {
                final String Emails=Email.getText().toString();
                final String Names = Name.getText().toString();
                final String User_Address = Address.getText().toString();
                final String Phone_number = phone_number.getText().toString();
                final String User_Age = Age.getText().toString();
                final String password=Password.getText().toString();

                final user_signup info=new user_signup(Names,User_Address,User_Age,Gender,Phone_number,Emails,unique_key,user.getUid());

                mAuth.createUserWithEmailAndPassword(Emails, password)
                        .addOnCompleteListener(User_registration_page.this, new OnCompleteListener<AuthResult>() {
                            @Override
                            public void onComplete(@NonNull Task<AuthResult> task) {
                                if (task.isSuccessful()) {

                                    FirebaseDatabase.getInstance().getReference("user_signup").child(mAuth.getCurrentUser().getUid())
                                            .setValue(info).addOnCompleteListener(new OnCompleteListener<Void>() {
                                        @Override
                                        public void onComplete(@NonNull Task<Void> task) {
                                            if (task.isSuccessful()) {

                                                register.setVisibility(View.INVISIBLE);
                                                final LottieAnimationView lottiePreloader=findViewById(R.id.preloader_button);

                                                lottiePreloader.setVisibility(View.VISIBLE);
                                                lottiePreloader.setSpeed(1);
                                                lottiePreloader.playAnimation();

                                                Thread timer = new Thread() {
                                                    public void run() {
                                                        try {
                                                            sleep(3000);
                                                        } catch (InterruptedException e) {
                                                            e.printStackTrace();
                                                        } finally {
                                                            Intent intent = new Intent(User_registration_page.this, User_Homepage.class);
                                                            startActivity(intent);
                                                            finish();
                                                        }
                                                    }
                                                };
                                                timer.start();

                                            } else {
                                                Toast.makeText(User_registration_page.this, "Authentication failed.",
                                                        Toast.LENGTH_SHORT).show();
                                            }
                                        }
                                    });

                                } else {
                                    Toast.makeText(User_registration_page.this, "Authentication failed.",
                                            Toast.LENGTH_SHORT).show();
                                }
                            }
                        });
                //code ends
            }
        /*  */

    }

    public String unique_key(){

        int length=5,i;
        char [] charr="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789".toCharArray();
        StringBuilder stringBuilder=new StringBuilder();
        Random random=new Random();
        for( i=0;i<length;i++){
            char c=charr[random.nextInt(charr.length)];
            stringBuilder.append(c);
        }
        return stringBuilder.toString();
    }
}